# Intermediate container, this will be disposed in the final image
FROM node:10 as node-builder
ARG CONFIG_FILE_NAME
WORKDIR /home/gigasource
RUN mkdir -p /home/gigasource/storage
COPY . .
# Set access token to access private github repositories then start building
RUN mv ./ssh ~/.ssh && \
    chmod -R 700 ~/.ssh && \
    npm install --unsafe-perm && \
    mv ./cms-configs/$CONFIG_FILE_NAME ./config/config.json && \
    npm run install-plugins && \
    npm run build
# Build electrion
RUN apt update && \
    apt install zip -y && \
    apt install wine64 -y && \
    apt install sshpass -y && \
    cd pkg && \
    npm install && \
    npm run build:win32 && \
    cd ../electron && \
    npm install && \
    npm run dist:win32 && \
    cd .. && \
    mv electron.zip pos-restaurant-electron.zip
RUN GIGASOURCE_ACCESS_TOKEN=$(cat ./gigasource-access-token) && \
    /bin/bash ./cicd/scripts/upload-github-release-asset.sh github_api_token=$GIGASOURCE_ACCESS_TOKEN owner=gigasource repo=cms-boilerplate-pos tag=pos filename=./pos-restaurant-electron.zip
# Build android
RUN GIGASOURCE_ACCESS_TOKEN=$(cat ./gigasource-access-token) && \
    cd android && \
    git clone --depth=1 --branch pos-restaurant git@github.com:gigasource/pos-android.git && \
    cd pos-android && \
    cd app && \
    curl -H "Authorization: token $GIGASOURCE_ACCESS_TOKEN" -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/gigasource/key-files/contents/pos-restaurant-android/build.gradle && \
    curl -H "Authorization: token $GIGASOURCE_ACCESS_TOKEN" -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/gigasource/key-files/contents/pos-restaurant-android/pos-android-key-store && \
    cd ../../../pkg && \
    npm install && \
    npm run build:android && \
    cd ..
# Download original apk and update patch
RUN chmod -R 700 ./ssh.cfg && \
    chmod -R 700 ./cicd/scripts/create-patch-file.sh && \
    ./ssh.cfg && \
    rm -rf /var/jenkins_home/files/feed2wall/apk && \
    mkdir -p /var/jenkins_home/files/feed2wall/apk && \
    echo $pwd && \
    sshpass -p ${pwd} scp -r ${usr}@${domain}:/home/dev/tinker-server/archive/posRestaurantPatching/* /var/jenkins_home/files/feed2wall/apk/ && \
    echo "Download finished" && \
    ./cicd/scripts/create-patch-file.sh

# Build new apk
FROM thyrlian/android-sdk
COPY --from=node-builder /home/gigasource /home/gigasource
WORKDIR /home/gigasource
RUN apt update && apt install curl -y && \
    cd ./android/pos-android && \
    ./gradlew build && \
    mv ./app/build/outputs/apk/release/app-release.apk /home/gigasource/pos-restaurant-app-release.apk
RUN GIGASOURCE_ACCESS_TOKEN=$(cat ./gigasource-access-token) && \
    ./cicd/scripts/upload-github-release-asset.sh github_api_token=$GIGASOURCE_ACCESS_TOKEN owner=gigasource repo=cms-boilerplate-pos tag=pos filename=./pos-restaurant-app-release.apk

# Cleanup unused & sensitive files
WORKDIR /home/gigasource
RUN rm -rf ./backoffice && \
    rm -rf ./cms-configs && \
    rm -rf ~/.ssh
