# Intermediate container, this will be disposed in the final image
FROM node:10 as node-builder
ARG CONFIG_FILE_NAME
WORKDIR /home/gigasource
RUN mkdir -p /home/gigasource/storage
COPY . .
# Set access token to access private github repositories then start building
RUN GIGASOURCE_ACCESS_TOKEN=$(cat ./gigasource-access-token)
RUN mv ./ssh ~/.ssh && \
    chmod -R 700 ~/.ssh && \
    npm install --unsafe-perm && \
    mv ./cms-configs/$CONFIG_FILE_NAME ./config/config.json && \
    npm run install-plugins && \
    npm run build
RUN cd android && \
    git clone --depth=1 --branch pos-restaurant git@github.com:gigasource/pos-android.git && \
    cd pos-android && \
    cd app && \
    curl -H 'Authorization: token $GIGASOURCE_ACCESS_TOKEN' -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/gigasource/key-files/contents/pos-restaurant-android/build.gradle && \
    curl -H 'Authorization: token $GIGASOURCE_ACCESS_TOKEN' -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/gigasource/key-files/contents/pos-restaurant-android/pos-android-key-store && \
    cd ../../../pkg && \
    npm install && \
    npm run build:android

FROM thyrlian/android-sdk
COPY --from=node-builder /home/gigasource /home/gigasource
WORKDIR /home/gigasource
RUN apt update && apt install curl -y && \
    cd ./android/pos-android && \
    ./gradlew build && \
    mv ./app/build/outputs/apk/release/app-release.apk /home/gigasource/pos-restaurant-app-release.apk
RUN GIGASOURCE_ACCESS_TOKEN=$(cat ./gigasource-access-token) && \
    ./cicd/scripts/upload-github-release-asset.sh github_api_token=$GIGASOURCE_ACCESS_TOKEN owner=gigasource repo=cms-boilerplate-pos tag=pos filename=./pos-restaurant-app-release.apk

# Cleanup unused & sensitive files
WORKDIR /home/gigasource
RUN rm -rf ./backoffice && \
    rm -rf ./cms-configs && \
    rm -rf ~/.ssh
