pipeline {
  agent any

  stages {
    stage('Prepare files and folders') {
      steps {
        withCredentials([string(credentialsId: 'gitbot-access-token', variable: 'GITBOT_ACCESS_TOKEN')]) {
          sh "echo $GITBOT_ACCESS_TOKEN > ./gitbot-access-token"
        }
        withCredentials([string(credentialsId: 'gigasource-github-access-token', variable: 'GIGASOURCE_ACCESS_TOKEN')]) {
          sh "echo $GIGASOURCE_ACCESS_TOKEN > ./gigasource-access-token"
        }
        sh "cp -r ~/.ssh ./ssh"
        sh "mkdir -p ./config"
        sh "mkdir -p ./plugins"
        sh "cp /var/jenkins_home/files/feed2wall/ssh.cfg ./"
      }
    }

    stage('Build Docker image') {
      steps {
        script {
          CURRENT_DATETIME = sh (
                  script: "date +%Y-%m-%d_%Hh.%Mm.%Ss",
                  returnStdout: true
          ).trim()

          if (env.dockerfileLocation != null) env.DOCKERFILE_LOCATION = env.dockerfileLocation
          else env.DOCKERFILE_LOCATION = "./cicd/Dockerfile"
        }

        script {image = docker.build("${env.dockerImageName}:$CURRENT_DATETIME", "-f ${env.DOCKERFILE_LOCATION} --no-cache=true --build-arg CONFIG_FILE_NAME=${env.configFileName} .")}
      }
    }

    stage('Remove locally built Docker image') {
      steps {
        sh "docker rmi $dockerImageName:$CURRENT_DATETIME"
      }
    }

    stage('Cleanup workspace') {
      steps {
        sh "rm -rf ./ssh ./gitbot-access-token ./config"
      }
    }
  }
}
